services:
  kafka:
    image: docker.io/bitnami/kafka:3.6
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      # KRaft settings
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      # Listeners
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT

  eureka:
    image: ${HS_EUREKA_IMAGE:-mhws/hs-eureka:latest}
    ports:
      - ${HS_EUREKA_PORT:-8325}:8761

  postgres:
    image: postgres:16.0-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DATABASE: db_box_office
      HS_POSTGRES_USERNAME: hs
      HS_POSTGRES_PASSWORD: example
    ports:
      - ${HS_BOX_OFFICE_POSTGRES_PORT:-8322}:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./services/postgres/entrypoint/:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_box_office"]
      start_period: 60s
      interval: 10s
      timeout: 60s
      retries: 5

  liquibase:
    image: liquibase/liquibase:4.24-alpine
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      LIQUIBASE_COMMAND_USERNAME: hs
      LIQUIBASE_COMMAND_PASSWORD: example
      LIQUIBASE_COMMAND_URL : jdbc:postgresql://postgres:5432/db_box_office
    volumes:
      - ./services/liquibase/changelog:/liquibase/changelog
      - ./services/liquibase/liquibase.box-office.properties:/liquibase/liquibase.properties
    command: --defaults-file=/liquibase/liquibase.properties update

  application:
    build:
      context: .
      dockerfile: dockerfile
    depends_on:
      liquibase:
        condition: service_completed_successfully
    ports:
      - ${HS_BOX_OFFICE_PORT:-8320}:9009
    environment:
      HS_BOX_OFFICE_EUREKA_URI: http://eureka:8761/eureka
      HS_BOX_OFFICE_DATASOURCE_HOST: postgres 
      HS_BOX_OFFICE_DATASOURCE_PORT: 5432
      HS_BOX_OFFICE_DATASOURCE_DATABASE: db_box_office
      HS_BOX_OFFICE_DATASOURCE_USERNAME: hs
      HS_BOX_OFFICE_DATASOURCE_PASSWORD: example

volumes:
  postgres-data:
  kafka_data:
