server:
  port: 9009

spring:
  application:
    name: hs-box-office
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/ms2
    username: postgres
    password: ${HS_BOX_PASSWORD}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


